[book]
authors = ["mortii"]
language = "en"
multilingual = false
src = "src"
title = "AnkiMorphs"

[output.html]
git-repository-url = "https://github.com/mortii/anki-morphs"
edit-url-template = "hhttps://github.com/mortii/anki-morphs/edit/website/docs/{path}"
additional-css = ["src/custom.css"]

[output.html.fold]
enable = true
level = 0

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.katex]
after = ["links"]
macros = "src/latex_macros.txt"
